image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - scala-lang.scala@0.3.9:kklqw+c/dNRmtTU8B5repw==
    - scalameta.metals@1.9.0:PtE/gdeE1YPL6It4tEfqpg==

tasks:
  - init: "mkdir -p .vscode && echo '{\"metals.sbtScript\": \"/home/gitpod/.local/share/coursier/bin/sbt\"}' > .vscode/settings.json"

ports:
  - port: 8212
    onOpen: ignore
