language: scala
jdk: openjdk8
git:
  depth: false
script: scripts/travis.sh
sudo: false
cache:
  directories:
  - $HOME/.cache
  - $HOME/.ivy2/cache
  - $HOME/.sbt
branches:
  only:
  - master
  - /^v\d+\.\d+.*$/ # tagged versions
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
  - scala: 2.12.10
  - scala: 2.13.1
  - stage: release
    script: sbt ci-release
